# Generated by Django 5.1 on 2024-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='profile_url',
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to='clients/'),
        ),
        migrations.AddField(
            model_name='imagemedia',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='testimonials/'),
        ),
    ]
