# Generated by Django 5.1 on 2024-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_client_image_url_remove_imagemedia_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='imagemedia',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
